import json

from azure.ai.inference.models._models import ChatRequestSystemMessage, ChatRequestUserMessage

from azdev.operations.command_change.extractor.utils import chat_client_4o_mini

LOGIC_SUMMARIZATION_PROMPT = """
You are a helpful Python Static Analysis Assistant. You will receive:
1. A Python Code Snippet
2. A JSON list describe all related call Usage in the Code Snippet
Your task is to summarize the running logic of code.

---Goal---
Your goal is to produce a concise and accurate summary of the code’s runtime logic.

You should:
* Focus on the overall logic and flow of the function, not just parameter descriptions.
* Incorporate insights from the related method calls to enrich your understanding of the function’s behavior.
* Avoid restating the code line-by-line; instead, abstract and explain what the code is doing at a higher level.
* If the function is large or complex, prioritize summarizing the main control flow, key operations, and purpose.

---Output Format---
Return a single paragraph that clearly describes the logic and purpose of the code snippet.

---Input---
Code Snippet:
{code_snippet}

Related Call Usage:
{call_usage}
"""

LOGIC_DETAIL_PROMPT="""
You are a meticulous Python Code Explainer. Your task is to produce a comprehensive, step-by-step explanation of a Python code snippet. You will receive:
* A Python code snippet
* A JSON list describing all related method calls used within the code snippet, including their names, parameters, and descriptions
* A high-level summary of the code’s logic (generated by a previous assistant)

---Goal---
Your goal is to expand the summary into a detailed explanation that includes:
* A line-by-line or block-by-block breakdown of the code’s logic
* Clear descriptions of control flow, data transformations, and key operations
* Integration of relevant information from the related method calls to explain what each function or method does
* Clarification of how each part of the code contributes to the overall behavior
* No omission of any logic present in the code snippet

---Constraints---
* Do not include any code snippets in the output
* Do not analyze or reference code comments related to tools like pylint

--Output Format---
Return a detailed explanation in natural language that fully describes the code’s behavior and logic, using the previous summary as a foundation and enriching it with all available details.

---Input---
Code Snippet:
{code_snippet}

Related Call Usage:
{call_usage}

Previous Summary:
{previous_summary}

"""

ARGS_SUMMARIZATION_PROMPT = """
You are a helpful Python Static Analysis Assistant. You will receive:
1. A Python Code Snippet
2. A JSON list describe all related call Usage in the Code Snippet
Your task is to  analyze the usage of each argument in the code snippet.

---Output Format---
Return a JSON  array of argument descriptors, each including:
* "name" which is the name of the parameter
* "type" (if annotated)
* "description"
* "usage" which is how the argument is used in the code snippet, including method calls, assignments, and any other relevant operations. The usage field should detail how the argument is used throughout the full code snippet and should be associated with the call map. If an argument is passed to functions in the call map, the usage should read like 'then in function_name, the argument is used as parameter_name to perform action_description'.

---Example Output---
[
    {{
        "name": "argument name",
        "type": "annotated type like str, str | None, ClassA",
        "description": "A description of the argument, indicating whether it is optional, positional, or a keyword argument, and its purpose",
        "usage": "A detailed description of how the argument is used in the code snippet, including method calls, assignments, and any other relevant operations. For example, 'then in function_name, the argument is used as parameter_name to perform action_description'."
    }}
]

---Additional Instructions---
1. Ensure that the usage field is comprehensive and covers all instances where the argument is used in the code snippet.
2. If the argument is passed to multiple functions, describe its usage in each function separately.
3. Include any relevant context or additional information that may help in understanding the argument's usage.

---Input---
Code Snippet:
{code_snippet}

Related Call Usage:
{call_usage}
"""

RETURN_SUMMARIZATION_PROMPT = """
You are a helpful Python Static Analysis Assistant. You will receive:
1. A Python Code Snippet
2. A JSON list describe all related call Usage in the Code Snippet
Your task is to analyze the type of possible returns.

---Output Format---
Return a JSON list of probable return type, each item is a JSON object with "name" and "package"(optional) field
* "name": type name
* "package": optional package name the type belongs to
* "description": A description of what the return type represents.

---Example Output---
[
    {{
        "name": "ReturnType",
        "package": "package.name",
        "description": "A description of what the return type represents."
    }}
]

---Input---
Code Snippet:
{code_snippet}

Related Call Usage:
{call_usage}
"""

EXCEPTION_SUMMARIZATION_PROMPT = """
You are a helpful Python Static Analysis Assistant. You will receive:
1. A Python Code Snippet
2. A JSON list describe all related call Usage in the Code Snippet
Your task is to analyze the types of exceptions that could potentially be raised during execution.

---Output Format---
Return a JSON list of probable raised exception types, each item is a JSON object with "name" and "package"(optional) field
* "name": type name
* "package": The package or module the exception belongs to (e.g., "builtins", "requests", "package.name")
* "description": A concise explanation of what the exception represents
* "condition": A detailed explanation of the specific condition under which the exception might be raised, based on the arguments and context of the call in the code snippet
**IMPORTANT:**
* If an exception is explicitly caught and handled in the code snippet, it should be excluded from the output.
* The "condition" field should describe the specific scenario under which the exception might be raised. This should be derived primarily from the call_usage data, but must be updated based on the actual context in the code_snippet. Specifically:
    * If the arguments in the code_snippet override or specialize the usage pattern described in call_usage, update the "condition" to reflect the actual argument values.
    * If the call described in call_usage is only invoked under a specific condition in the code_snippet (e.g., inside an if block, guarded by a try-except, or dependent on a variable state), incorporate that condition into the "condition" field.
* Use the actual argument values from the code_snippet to make the "condition" as specific, contextual, and informative as possible. Avoid generic phrases when concrete values or logic are available.

---Example Output---

[
    {{
        "name": "ValueError",
        "package": "builtins",
        "description": "Raised when a function receives an argument of the correct type but an inappropriate value.",
        "condition": "When the 'mode' argument is set to 'invalid_mode', which is not supported by the function."
    }},
    {{
        "name": "KeyError",
        "package": "builtins",
        "description": "Raised when a dictionary key is not found.",
        "condition": "When accessing 'config['timeout']' and the 'timeout' key is missing from the 'config' dictionary."
    }}
]


---Input---
Code Snippet:
{code_snippet}

Related Call Usage:
{call_usage}
"""


def logic_summarize(code_snippet, call_usage, client=None):
    if not client:
        client = chat_client_4o_mini()
    resp = client.complete(
        messages=[
            ChatRequestSystemMessage(
                content=LOGIC_SUMMARIZATION_PROMPT.format(
                    code_snippet=code_snippet and code_snippet[:50000],
                    call_usage=json.dumps(call_usage)[:50000],
                ),
            ),
            ChatRequestUserMessage(
                content='Please give the result in correct format.'
            )
        ],
        max_tokens=1000,
    )

    content = resp.choices[0].message.content
    return content

def logic_detail(code_snippet, call_usage, previous_summary, client=None):
    if not client:
        client = chat_client_4o_mini()
    resp = client.complete(
        messages=[
            ChatRequestSystemMessage(
                content=LOGIC_DETAIL_PROMPT.format(
                    code_snippet=code_snippet and code_snippet[:50000],
                    call_usage=json.dumps(call_usage)[:50000],
                    previous_summary=previous_summary[:1000]
                ),
            ),
            ChatRequestUserMessage(
                content='Please give the result in correct format.'
            )
        ],
        max_tokens=10000,
    )

    content = resp.choices[0].message.content
    return content

def args_summarize(code_snippet, call_usage, client=None):
    if not client:
        client = chat_client_4o_mini()
    resp = client.complete(
        messages=[
            ChatRequestSystemMessage(
                content=ARGS_SUMMARIZATION_PROMPT.format(
                    code_snippet=code_snippet and code_snippet[:50000],
                    call_usage=json.dumps(call_usage)[:50000],
                ),
            ),
            ChatRequestUserMessage(
                content='Please give the result in correct format.'
            )
        ],
        response_format='json_object',
        max_tokens=10000,
    )

    content = resp.choices[0].message.content
    content_object = json.loads(content)
    return content_object

def return_summarize(code_snippet, call_usage, client=None):
    if not client:
        client = chat_client_4o_mini()
    resp = client.complete(
        messages=[
            ChatRequestSystemMessage(
                content=RETURN_SUMMARIZATION_PROMPT.format(
                    code_snippet=code_snippet and code_snippet[:50000],
                    call_usage=json.dumps(call_usage)[:50000],
                ),
            ),
            ChatRequestUserMessage(
                content='Please give the result in correct format.'
            )
        ],
        response_format='json_object',
        max_tokens=1000,
    )

    content = resp.choices[0].message.content
    content_object = json.loads(content)
    return content_object

def exceptions_summarize(code_snippet, call_usage, client=None):
    if not client:
        client = chat_client_4o_mini()
    resp = client.complete(
        messages=[
            ChatRequestSystemMessage(
                content=EXCEPTION_SUMMARIZATION_PROMPT.format(
                    code_snippet=code_snippet and code_snippet[:50000],
                    call_usage=json.dumps(call_usage)[:50000],
                ),
            ),
            ChatRequestUserMessage(
                content='Please give the result in correct format.'
            )
        ],
        response_format='json_object',
        max_tokens=1000,
    )

    content = resp.choices[0].message.content
    content_object = json.loads(content)
    return content_object
